### ISSUE TITLE
Automate placing participants into topic channels

### ISSUE THREAD

**Issue by skyegallup** [codeRIT/mentorbot#6]
Current user flow ([discussed at Jan 30 meeting](https://www.notion.so/5e2364c0034d4ab681bb4f44dc67d04b?v=9f4b1470618844f897d212fc82e3bc5b&p=02f30ab1eb4e47609219127590fb53de)):
- User runs `$queue <topic>`
- Mentor runs `$ready <topic>`
- `<topic>` text/voice channels are created in `Mentoring` category
- Channels are deleted after user and mentor leave voice channel

Issues with flow:
- "user and mentor leave voice channel" assume voice channel use, which isn't very accessibility-friendly
  - Ask deaf/HoH users to join and leave voice channel?
  - Mentor runs `$finish` command inside text channel to end interaction?

**Comment by Madrugaur** [comment]
@colbygallup To jump off of what we have, I think we should implement the text-based mentoring system first and then implement a voice based one on top of it. This would make it so the mentor would be able to leave notes, resources, links, etc for the mentee to check out later on, no matter accessibility level. I think this would help lower the volume of queues and just be more convenient. If the mentee asks, the mentor (or bot on command) can post an invitation to a voice channel that is available for this "session"

**Comment by skyegallup** [comment]
Status update:
- Main flow described in issue text is complete
- `$finish` works
- Need to add support for multiple simultaneous mentor-user interactions. Right now, mentoring sessions have to occur one at a time, but that won't work with the volume of users we're looking at.
